---
openapi: 3.0.0
info:
  title: Eco Market API
  description: Market API for Eco game. Main API for website
  license:
    name: GPL v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/woody41/eco-market-api/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: TradeablesItem
  description: Tradeable Items controller
paths:
  /items:
    get:
      tags:
      - TradeablesItems
      summary: Gets all items
      description: |
        Returns all active items
      operationId: getItems
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeableItem'
        "400":
          description: bad input parameter
    post:
      tags:
      - TradeablesItems
      summary: Add new tradable item
      description: Adds an item to the system
      operationId: addItem
      requestBody:
        description: Inventory item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeableItem'
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
  /items/{itemId}:
    get:
      tags:
      - TradeablesItems
      summary: Gets all items
      description: |
        Returns all active items
      operationId: getItemById
      parameters:
      - name: itemId
        in: path
        description: ID of item
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeableItem'
        "404":
          description: Item not found
components:
  schemas:
    TradeableItem:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          example: 1564
        name:
          type: string
          example: Gold Bar
